import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Features from '@/components/Features'
import {  useState } from 'react';
import axios from 'axios'
const inter = Inter({ subsets: ['latin'] })




export default function Home({ pizzaList, admin }) {
  const [close, setClose] = useState(true)


  return (
    <div className={styles.container}>
      <Head>
        <title>PizzaBoy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Features/>
    </div>
  )
}

export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookies || "";
  let admin = false;

  if(myCookie.token === process.env.TOKEN) {
    admin = true
  }

  const res = await axios.get("https://pizza-boy.vercel.app/api/products");
  return {
    props: {
      pizzaList: res.data,
      admin
    },
  };
}

